export const iconStrings: Record<string, string> = {
  TypeScript: "nonicons:typescript-16",
  React: "nonicons:react-16",
  Python: "nonicons:python-16",
  "C++": "nonicons:c-plusplus-16",
  Docker: "nonicons:docker-16",
  Kubernetes: "nonicons:kubernetes-16",
  VSCode: "nonicons:vscode-16",
  Rust: "nonicons:rust-16",
  Go: "nonicons:go-16",
  Svelte: "nonicons:svelte-16",
  Vue: "nonicons:vue-16",
  Terraform: "nonicons:terraform-16",
  Angular: "nonicons:angular-16",
  Java: "nonicons:java-16",
  AWS: "mdi:aws",
  Azure: "mdi:azure",
  "Azure DevOps": "mdi:microsoft-azure-devops",
  DevContainer: "file-icons:devcontainer",
  Cloudfoundry: "simple-icons:cloudfoundry",
  Bitbucket: "mdi:bitbucket",
  Jenkins: "devicon-plain:jenkins",
  "GitHub Actions": "simple-icons:githubactions",
  Chef: "file-icons:chef",
  Redux: "file-icons:redux",
  "GitLab CI": "mdi:gitlab",
};
